import type { Metadata } from "next";
;

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className="bg-slate-950">
      <body className="bg-slate-950">
        {children}
        </body>
    </html>
  );
}

